server:
  port: 81

spring:
  datasource:
   url: jdbc:mysql://localhost:3306/moneyleaf
   username: root
   password: Password@1234
   driver-class-name: com.mysql.jdbc.Driver
   dbcp2:
    max-idle: 20
    max-wait-millis: 20000
    min-idle: 15 
  
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  auth:
    tokenCheckPointUrl: http://localhost:81/auth/validateAcccessToken
    tokenSecret: ZmRmNGI0YzZjZGI0ZDkxOGYyMjBlN2MzMGFlMjUyMDk1YWFjZDM3N2QwMWViNjkzNTkwMTgyYTc4MjA4ZWY0OTNkOTg3YWE5ZGVkNzJkYzQwODIyNzRhY2ZiYjVjYzQwOTFiODk4MGVkMDFhYmJmNmEwNDBjNzNkMjBjMzk2YjM