server:
  port: 8080

spring:
  datasource:
   url: jdbc:mysql://google/sanchay?cloudSqlInstance=sanchay-274309:asia-south1:sanchay-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory
   username: root
   password: Password@1234
   driver-class-name: com.mysql.jdbc.Driver
   dbcp2:
    max-idle: 20
    max-wait-millis: 20000
    min-idle: 15
   
  
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: https://sanchay-discovery-server-dot-sanchay-274309.el.r.appspot.com/eureka

app:
  auth:
    tokenCheckPointUrl: https://sanchay-uaa-dot-sanchay-274309.el.r.appspot.com/auth/validateAcccessToken
    tokenSecret: ZmRmNGI0YzZjZGI0ZDkxOGYyMjBlN2MzMGFlMjUyMDk1YWFjZDM3N2QwMWViNjkzNTkwMTgyYTc4MjA4ZWY0OTNkOTg3YWE5ZGVkNzJkYzQwODIyNzRhY2ZiYjVjYzQwOTFiODk4MGVkMDFhYmJmNmEwNDBjNzNkMjBjMzk2YjM
  