env: flex
runtime: java
service: sanchay-calc-service
resources:
  cpu: 1
  memory_gb: 3
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5
automatic_scaling:
  max_num_instances: 1
env_variables:
  SPRING_PROFILES_ACTIVE: "prod"